name: Changeset Publish

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    branches: [ main ]

permissions:
  contents: write

jobs:
  publish:
    name: Create Git Tag
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true &&
       (startsWith(github.event.pull_request.head.ref, 'release/') ||
        startsWith(github.event.pull_request.head.ref, 'release/')))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version from CHANGELOG
        id: version
        run: |
          # Get the first version header from CHANGELOG.md (e.g., "## 1.2.3" or "## v1.2.3")
          VERSION=$(grep -m1 -oE '^## v?[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ steps.version.outputs.version }}" -m "Release v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"

      - name: Create GitHub Release
        uses: actions/github-script@v7
        with:
          script: |
            const version = '${{ steps.version.outputs.version }}';
            const tag = `v${version}`;

            // Get changelog content for this version
            const fs = require('fs');
            let changelog = '';
            try {
              const content = fs.readFileSync('CHANGELOG.md', 'utf8');
              const regex = new RegExp(`## v?${version}[\\s\\S]*?(?=## v?\\d|$)`);
              const match = content.match(regex);
              if (match) {
                changelog = match[0].trim();
              }
            } catch (e) {
              changelog = `Release ${tag}`;
            }

            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: tag,
              body: changelog,
              draft: false,
              prerelease: false
            });
