name: Changeset Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Check for changeset
    runs-on: ubuntu-latest
    # Never block the PR - this is informational only
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read config
        id: config
        run: |
          # Read release branch prefix from config (default: changeset-release/)
          PREFIX=$(jq -r '.releaseBranchPrefix // "changeset-release/"' .changes/config.json)
          echo "release_branch_prefix=$PREFIX" >> $GITHUB_OUTPUT

      - name: Check if release PR
        id: release-check
        run: |
          # Skip release PRs - they don't need changesets
          HEAD_REF="${{ github.head_ref }}"
          PREFIX="${{ steps.config.outputs.release_branch_prefix }}"
          if [[ "$HEAD_REF" == release/* ]] || [[ "$HEAD_REF" == ${PREFIX}* ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for changeset files
        if: steps.release-check.outputs.is_release == 'false'
        id: changeset-check
        run: |
          # Get list of changed files in this PR
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD 2>/dev/null || echo "")

          # Check if any .changes/*.md files were added (excluding README.md)
          CHANGESET_FILES=$(echo "$CHANGED_FILES" | grep -E '^\.changes/.*\.md$' | grep -v 'README.md' || true)

          if [ -z "$CHANGESET_FILES" ]; then
            echo "has_changeset=false" >> $GITHUB_OUTPUT
            echo "No changeset found in this PR"
          else
            echo "has_changeset=true" >> $GITHUB_OUTPUT
            echo "Found changesets:"
            echo "$CHANGESET_FILES"
          fi

      - name: Comment on PR
        if: steps.release-check.outputs.is_release == 'false' && steps.changeset-check.outputs.has_changeset == 'false'
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            const body = `### 📝 No Changeset Found

            This PR does not include a changeset. If this change should be included in the changelog and trigger a release, please add one:

            \`\`\`bash
            champ add
            \`\`\`

            If this change doesn't need a release (e.g., docs, tests, CI), you can ignore this message.

            <details>
            <summary>What is a changeset?</summary>

            A changeset is a markdown file in the \`.changes/\` directory that describes what changed and how it affects the version number (major, minor, or patch).

            </details>`;

            // Check if we already commented
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('No Changeset Found')
            );

            if (!botComment) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }
