name: Changeset Release

on:
  push:
    branches: [main]
    paths:
      - '.changes/*.md'
      - '!.changes/README.md'

jobs:
  release:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Check for changesets
        id: check
        run: |
          # Count changeset files (excluding README.md)
          COUNT=$(find .changes -name "*.md" ! -name "README.md" 2>/dev/null | wc -l | tr -d ' ')
          echo "changeset_count=$COUNT" >> $GITHUB_OUTPUT
          echo "has_changesets=$([[ $COUNT -gt 0 ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

          if [ "$COUNT" -gt 0 ]; then
            echo "Found $COUNT changeset(s)"
          else
            echo "No changesets found"
          fi

      - name: Run cc version
        if: steps.check.outputs.has_changesets == 'true'
        run: |
          # Run version command non-interactively
          echo "y" | ./vendor/bin/cc version

      - name: Get new version
        if: steps.check.outputs.has_changesets == 'true'
        id: version
        run: |
          # Get the first version header from CHANGELOG.md (e.g., "## 0.1.0")
          VERSION=$(grep -m1 -oE '^## [0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check.outputs.has_changesets == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: release v${{ steps.version.outputs.version }}"
          title: "chore: release v${{ steps.version.outputs.version }}"
          body: |
            ## Release v${{ steps.version.outputs.version }}

            This PR was automatically created by the changeset release workflow.

            ### Changes
            - Updated `CHANGELOG.md` with v${{ steps.version.outputs.version }} entry
            - Deleted processed changeset files

            ### Next Steps
            1. Review the changes
            2. Merge this PR
            3. The release will be tagged automatically

            ---
            🤖 This PR was auto-generated by [change-champion](https://github.com/offload-project/change-champion)
          branch: changeset-release/v${{ steps.version.outputs.version }}
          delete-branch: true
          labels: |
            release
            automated
